export enum ChartType {
	// Camera
	FISH_DENSITY = 'FISH_DENSITY',
	IMAGE_QUALITY = 'IMAGE_QUALITY',
	FISH_ANALYZED_FOR_LICE = 'FISH_ANALYZED_FOR_LICE',
	FISH_ANALYZED_FOR_BIOMASS = 'FISH_ANALYZED_FOR_BIOMASS',
	TEMPERATURE = 'TEMPERATURE',
	DEPTH = 'DEPTH',
	TILT = 'TILT',

	// Lice
	LICE = 'LICE',
	LICE_FORECAST = 'LICE_FORECAST',
	LICE_HEAT_MAP = 'LICE_HEAT_MAP',

	// Biomass
	AVERAGE_WEIGHT = 'AVERAGE_WEIGHT',
	INDIVIDUAL_WEIGHT = 'INDIVIDUAL_WEIGHT',
	K_FACTOR = 'K_FACTOR',
	WEIGHT_DIST = 'WEIGHT_DIST',
	WEIGHT_DIST_K_FACTOR = 'WEIGHT_DIST_K_FACTOR',

	// Fish group
	RAILWAY = 'RAILWAY',

	// Health
	AVERAGE_SWIMMING_SPEED = 'AVERAGE_SWIMMING_SPEED',
	PERCENT_WOUNDED = 'PERCENT_WOUNDED',

	// Welfare
	// Skin
	BODY_WOUND = 'BODY_WOUND',
	SCALE_LOSS = 'SCALE_LOSS',
	SNOUT_DAMAGE = 'SNOUT_DAMAGE',

	// Deformity
	SPINE_DEFORMITY = 'SPINE_DEFORMITY',
	JAW_DEFORMITY = 'JAW_DEFORMITY',
	OPERCULAR_DAMAGE = 'OPERCULAR_DAMAGE',

	// Fin damage
	ANAL_FIN_DAMAGE = 'ANAL_FIN_DAMAGE',
	CAUDAL_FIN_DAMAGE = 'CAUDAL_FIN_DAMAGE',
	PECTORAL_FIN_DAMAGE = 'PECTORAL_FIN_DAMAGE',
	PELVIC_FIN_DAMAGE = 'PELVIC_FIN_DAMAGE',
	DORSAL_FIN_DAMAGE = 'DORSAL_FIN_DAMAGE',

	// Eye
	EYE_CLOUDING = 'EYE_CLOUDING',
	EYE_BLEEDING = 'EYE_BLEEDING',
	EYE_EXOPHTHALMOS = 'EYE_EXOPHTHALMOS',

	// Maturation
	MATURATION = 'MATURATION',
}
